# Generated by Django 2.2.4 on 2019-12-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('fee', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=200)),
                ('placed', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('review', models.CharField(max_length=200)),
            ],
        ),
    ]
